---
- name: Install docker apt key
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id="58118E89F3A912897C070ADBF76221572C52609D" state=present
  tags: docker

- name: Install docker apt repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present
  tags: docker

#- name: Uninstall docker
#  apt: name=lxc-docker update_cache=yes cache_valid_time=3600 state=absent purge=yes
#  tags: docker
#
#- name: Install docker
#  apt: name=docker-engine update_cache=yes cache_valid_time=3600 state=present
#  tags: docker

- name: Update docker config file
  template: src=docker.j2 dest=/etc/default/docker owner=root group=root mode=0644 force=true
  notify:
    - restart docker

